_mainIndex:
    pattern: /
    defaults : {_controller: ISGProjectSubmissionAppBundle:User:login }

_userLogin:
    pattern: /user/login
    defaults : {_controller: ISGProjectSubmissionAppBundle:User:login }

_userLogout:
    pattern : /user/logout
    defaults : {_controller: ISGProjectSubmissionAppBundle:User:logout }

_userProfile:
    prefix: /user/profile
    pattern: /user/profile
    defaults : {_controller: ISGProjectSubmissionAppBundle:User:profile }
    
_logout:
    pattern: /user/logout
    defaults : {_controller: ISGProjectSubmissionAppBundle:User:logout}

_userNew:
    pattern : /user/new
    defaults : {_controller: ISGProjectSubmissionAppBundle:User:new }

_userList:     
    pattern : /user/list
    defaults : {_controller: ISGProjectSubmissionAppBundle:User:list }

_userEdit:
    pattern : /user/edit/{id}
    defaults : {_controller: ISGProjectSubmissionAppBundle:User:edit }                

_userDelete:
    pattern : /user/delete/{id}
    defaults : {_controller: ISGProjectSubmissionAppBundle:User:delete }        
        
_user_show:
    pattern:  /user/show/{name}
    defaults: { _controller: ISGProjectSubmissionAppBundle:User:show }

