_mainIndex:
    pattern: /
    defaults: {_controller: ISGProjectSubmissionAppBundle:User:login }
    
  
_register:
    pattern: /register
    defaults : {_controller: ISGProjectSubmissionAppBundle:User:register }    

_user_show:
    pattern:  /user/show/{name}
    defaults: { _controller: ISGProjectSubmissionAppBundle:User:show }

    